### ISSUE TITLE
Java heap out of memory error

### ISSUE THREAD

**Issue by wanhuz** [kotcrab/szurubooru-auto-tagger#12]
I encounter **java.lang.OutOfMemoryError: Java heap space** error when running the program for the second time.

Command: `java -jar szubooru-auto-tagger-1.3.jar --config config-szu-tag.yaml`

`Szurubooru auto tagger
Using config from config-szu-tag.yaml
Booru connectivity looks ok
Reading tag map...
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:248)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
	at com.esotericsoftware.yamlbeans.tokenizer.Tokenizer.fetchMoreTokens(Tokenizer.java:312)
	at com.esotericsoftware.yamlbeans.tokenizer.Tokenizer.peekNextToken(Tokenizer.java:120)
	at com.esotericsoftware.yamlbeans.tokenizer.Tokenizer.peekNextTokenType(Tokenizer.java:125)
	at com.esotericsoftware.yamlbeans.parser.Parser$20.produce(Parser.java:320)
	at com.esotericsoftware.yamlbeans.parser.Parser.getNextEvent(Parser.java:80)
	at com.esotericsoftware.yamlbeans.parser.Parser.peekNextEvent(Parser.java:91)
	at com.esotericsoftware.yamlbeans.YamlReader.readValueInternal(YamlReader.java:270)
	at com.esotericsoftware.yamlbeans.YamlReader.readValue(YamlReader.java:152)
	at com.esotericsoftware.yamlbeans.YamlReader.read(YamlReader.java:103)
	at com.esotericsoftware.yamlbeans.YamlReader.read(YamlReader.java:90)
	at com.kotcrab.szurubooru.tagger.AutoTagger.readTagMap(AutoTagger.kt:82)
	at com.kotcrab.szurubooru.tagger.AutoTagger.<init>(AutoTagger.kt:66)
	at com.kotcrab.szurubooru.tagger.MainKt.main(Main.kt:55)`

Running the program with more memory does not fix the issue. Tried this with ~2.5gb (maximum I can allocate at my Raspberry Pi) but no luck.

Command: `java -Xmx2500m -jar szubooru-auto-tagger-1.3.jar --config config-szu-tag.yaml`

**Comment by kotcrab** [comment]
What's the size of your `tagMapFile` (by default `tagMap.yaml`)?. It's been years since I worked on this but the tag map is inefficient since it requires to be fully loaded into memory. Still, I can't imagine it being so huge to cause OOM, maybe the issue is with the yaml parser.

**Comment by wanhuz** [comment]
My tagfile size is 109K and only has 4170 lines.

**Comment by kotcrab** [comment]
Can you build/run from source code? I've swapped the yaml parser with a more common one but I don't really have the booru setup to test it properly.
It's possible too your tag map has some weird tag that messed up the parser.

**Comment by wanhuz** [comment]
Sure. I've run it from the source code and it works great so far. I've not yet run it to completion as there are many posts that need to be tagged but I think it's safe to say the changes work as the program no longer breaks after "Reading tag map...". Thank you. :)

`Szurubooru auto tagger
Using config from config-szu-tag.yaml
Booru connectivity looks ok
Reading tag map...
Obtaining tags...
URL http://192.168.9.244:8090/api/posts/?offset=0&limit=100&query=auto_tagme timed out. Retrying in 3 seconds...
URL http://192.168.9.244:8090/api/posts/?offset=100&limit=100&query=auto_tagme timed out. Retrying in 3 seconds...
URL http://192.168.9.244:8090/api/posts/?offset=200&limit=100&query=auto_tagme timed out. Retrying in 3 seconds...
URL http://192.168.9.244:8090/api/posts/?offset=300&limit=100&query=auto_tagme timed out. Retrying in 3 seconds...
URL http://192.168.9.244:8090/api/posts/?offset=400&limit=100&query=auto_tagme timed out. Retrying in 3 seconds...
URL http://192.168.9.244:8090/api/posts/?offset=500&limit=100&query=auto_tagme timed out. Retrying in 3 seconds...
URL http://192.168.9.244:8090/api/posts/?offset=600&limit=100&query=auto_tagme timed out. Retrying in 3 seconds...
URL http://192.168.9.244:8090/api/posts/?offset=700&limit=100&query=auto_tagme timed out. Retrying in 3 seconds...
URL http://192.168.9.244:8090/api/posts/?offset=800&limit=100&query=auto_tagme timed out. Retrying in 3 seconds...
URL http://192.168.9.244:8090/api/posts/?offset=900&limit=100&query=auto_tagme timed out. Retrying in 3 seconds...
URL http://192.168.9.244:8090/api/posts/?offset=1000&limit=100&query=auto_tagme timed out. Retrying in 3 seconds...
There are 1071 posts that needs to be tagged
Searching IQDB match for post 1079...
Found post 1079 match: https://danbooru.donmai.us/posts/2873430
Updated post 1079 source
Updated post 1079 safety to Safe
Found bigger version of post 1079, created comment.
Updated post 1079 tags. Completed 1/1071.
(rest omitted)`

**Comment by kotcrab** [comment]
Great, I'll upload the jar to releases. Just a heads up, I don't think you can stop it midway since that won't update [notes and tag metadata](https://github.com/kotcrab/szurubooru-auto-tagger/blob/master/src/main/kotlin/com/kotcrab/szurubooru/tagger/AutoTagger.kt#L260). This project is in a need of a rewrite to fix all the bad design decisions. I planned to do so but ultimately decided that szurubooru doesn't fit my needs. I think I should update the README to say that this project isn't really maintained.
